import { execFileSync } from 'node:child_process';
import {
	existsSync,
	mkdirSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	realpathSync,
	rmSync,
	unlinkSync,
	writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { getFileTreeResponse, readFileContent, writeFileContent } from '../src/services/context-explorer.service';
import { buildContextProposedEdits } from '../src/services/context-explorer-edit.service';
import {
	connectContextRepository,
	ContextRepositoryProvider,
	discardContextFileChange,
	getChangedContextFiles,
	getContextFileDiff,
} from '../src/services/context-explorer-git.service';
import { getCommittedProjectPaths, resolveContextRepo } from '../src/utils/context-repo';

describe('context explorer git operations', () => {
	let worktreeRoot: string;
	let projectFolder: string;

	beforeEach(() => {
		worktreeRoot = mkdtempSync(join(tmpdir(), 'nao-context-explorer-git-'));
		projectFolder = join(worktreeRoot, 'project');
		mkdirSync(projectFolder);
		initRepository(worktreeRoot);
		writeFileSync(join(projectFolder, 'plain.md'), 'committed plain\n');
		writeFileSync(
			join(projectFolder, 'generated.md'),
			'---\ntype: generated\ncomment: This file is managed and generated by the agent, do not modify it!\n---\ngenerated\n',
		);
		writeFileSync(join(projectFolder, 'manual.md'), '---\ntype: manual\n---\nmanual\n');
		writeFileSync(join(projectFolder, 'rendered.md'), 'rendered\n');
		writeFileSync(join(projectFolder, 'rendered.md.j2'), 'template\n');
		writeFileSync(join(worktreeRoot, 'outside.md'), 'outside committed\n');
		commitFiles(worktreeRoot);
		addGithubOrigin(worktreeRoot);
	});

	afterEach(() => {
		rmSync(worktreeRoot, { recursive: true, force: true });
	});

	it('resolves a GitHub origin and nested project prefix', () => {
		const repo = resolveContextRepo(projectFolder);

		expect(repo).toMatchObject({
			provider: 'github',
			repoFullName: 'nao/context',
			branch: 'main',
			projectPrefix: 'project',
			worktreeRoot: realpathSync(worktreeRoot),
		});
		expect(getCommittedProjectPaths(repo!)).toContain('plain.md');
		expect(getCommittedProjectPaths(repo!)).not.toContain('outside.md');
	});

	it('returns null when the repository has no origin', () => {
		runGit(worktreeRoot, ['remote', 'remove', 'origin']);

		expect(resolveContextRepo(projectFolder)).toBeNull();
	});

	it('returns a null branch for detached HEAD', () => {
		runGit(worktreeRoot, ['checkout', '--quiet', '--detach']);

		expect(resolveContextRepo(projectFolder)?.branch).toBeNull();
	});

	it('reports a repository with no commits clearly', () => {
		const emptyRepository = mkdtempSync(join(tmpdir(), 'nao-context-explorer-empty-'));
		try {
			initRepository(emptyRepository);
			addGithubOrigin(emptyRepository);
			const repo = resolveContextRepo(emptyRepository);

			expect(repo).not.toBeNull();
			expect(() => getCommittedProjectPaths(repo!)).toThrow('no commits yet');
		} finally {
			rmSync(emptyRepository, { recursive: true, force: true });
		}
	});

	it('applies every editability rule', async () => {
		writeFileSync(join(projectFolder, 'untracked.md'), 'untracked\n');
		const tree = await getFileTreeResponse(projectFolder);

		expect(tree.repo).toEqual({ provider: 'github', repoFullName: 'nao/context', branch: 'main' });
		expect(tree.entries.find((entry) => entry.name === 'plain.md')?.isTracked).toBe(true);
		expect(tree.entries.find((entry) => entry.name === 'untracked.md')?.isTracked).toBe(false);
		await expect(readFileContent('/plain.md', projectFolder)).resolves.toMatchObject({
			isEditable: true,
			editabilityReason: null,
		});
		await expect(readFileContent('/untracked.md', projectFolder)).resolves.toMatchObject({
			isEditable: false,
			editabilityReason: 'not-tracked',
		});
		await expect(readFileContent('/generated.md', projectFolder)).resolves.toMatchObject({
			isEditable: false,
			editabilityReason: 'generated',
		});
		await expect(readFileContent('/manual.md', projectFolder)).resolves.toMatchObject({
			isEditable: true,
			editabilityReason: null,
		});
		await expect(readFileContent('/rendered.md', projectFolder)).resolves.toMatchObject({
			isEditable: false,
			editabilityReason: 'rendered-template',
		});
	});

	it('forbids writes with the specific read-only reason', async () => {
		writeFileSync(join(projectFolder, 'untracked.md'), 'untracked\n');

		await expectWriteForbidden('/untracked.md', 'not committed');
		await expectWriteForbidden('/generated.md', 'generated by nao');
		await expectWriteForbidden('/rendered.md', 'rendered from a Jinja template');

		runGit(worktreeRoot, ['remote', 'remove', 'origin']);
		await expectWriteForbidden('/plain.md', 'no GitHub or GitLab origin');
	});

	it('reports only project changes with their kinds and preserves spaces', () => {
		writeFileSync(join(projectFolder, 'plain.md'), 'changed plain\n');
		writeFileSync(join(projectFolder, 'new file.md'), 'new\n');
		unlinkSync(join(projectFolder, 'manual.md'));
		writeFileSync(join(worktreeRoot, 'outside.md'), 'outside changed\n');

		expect(getChangedContextFiles(projectFolder)).toEqual([
			{ path: '/manual.md', kind: 'deleted' },
			{ path: '/new file.md', kind: 'untracked' },
			{ path: '/plain.md', kind: 'modified' },
		]);
	});

	it('returns old and new content for modified and untracked files', async () => {
		writeFileSync(join(projectFolder, 'plain.md'), 'changed plain\n');
		writeFileSync(join(projectFolder, 'new file.md'), 'new\n');

		await expect(getContextFileDiff('/plain.md', projectFolder)).resolves.toEqual({
			path: '/plain.md',
			kind: 'modified',
			oldContent: 'committed plain\n',
			newContent: 'changed plain\n',
		});
		await expect(getContextFileDiff('/new file.md', projectFolder)).resolves.toEqual({
			path: '/new file.md',
			kind: 'untracked',
			oldContent: '',
			newContent: 'new\n',
		});
	});

	it('restores committed content and rejects untracked files', () => {
		writeFileSync(join(projectFolder, 'plain.md'), 'changed plain\n');
		writeFileSync(join(projectFolder, 'untracked.md'), 'untracked\n');

		const result = discardContextFileChange('/plain.md', projectFolder);

		expect(readFileSync(join(projectFolder, 'plain.md'), 'utf-8')).toBe('committed plain\n');
		expect(result.hash).toMatch(/^[a-f0-9]{64}$/);
		expect(() => discardContextFileChange('/untracked.md', projectFolder)).toThrow('nothing to restore');
	});

	it('assembles selected edits without provider access', async () => {
		writeFileSync(join(projectFolder, 'plain.md'), 'changed plain\n');

		await expect(buildContextProposedEdits(projectFolder, ['/plain.md'])).resolves.toEqual([
			{
				path: 'plain.md',
				kind: 'edit',
				oldContent: 'committed plain\n',
				newContent: 'changed plain\n',
			},
		]);
		await expect(buildContextProposedEdits(projectFolder, ['/generated.md'])).rejects.toMatchObject({
			code: 'FORBIDDEN',
		});
	});

	async function expectWriteForbidden(filePath: string, message: string): Promise<void> {
		const current = await readFileContent(filePath, projectFolder);
		await expect(writeFileContent(filePath, 'changed\n', current.hash, projectFolder)).rejects.toMatchObject({
			code: 'FORBIDDEN',
			message: expect.stringContaining(message),
		});
	}
});

describe('connecting a context repository', () => {
	const temporaryFolders: string[] = [];

	afterEach(() => {
		for (const folder of temporaryFolders.splice(0)) {
			rmSync(folder, { recursive: true, force: true });
		}
		delete process.env.NAO_CONTEXT_SOURCE;
	});

	it('links to an existing commit without changing any working-tree file bytes', async () => {
		const remote = createRemoteRepository(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: remote\n'),
			'context/model.md': Buffer.from([0, 1, 2, 3, 255]),
		});
		const project = createProjectFolder(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: deployed\n'),
			'context/model.md': Buffer.from([0, 1, 9, 3, 255]),
			'instance-only.md': Buffer.from('instance\n'),
		});
		const before = snapshotWorkingFiles(project);
		const remoteHead = runGit(remote.seed, ['rev-parse', 'HEAD']).toString().trim();

		const result = await connectContextRepository(connectionInput(project), testProvider(remote.bare));

		expect(result.connectionType).toBe('linked-existing-commit');
		expect(runGit(project, ['remote', 'get-url', 'origin']).toString().trim()).toBe(
			'https://github.com/nao/connected.git',
		);
		expect(runGit(project, ['rev-parse', 'HEAD']).toString().trim()).toBe(remoteHead);
		expect(snapshotWorkingFiles(project)).toEqual(before);
	});

	it('reports no changes when instance and repository content match', async () => {
		const files = {
			'nao_config.yaml': Buffer.from('project_name: same\n'),
			'context/model.md': Buffer.from('same\n'),
		};
		const remote = createRemoteRepository(temporaryFolders, files);
		const project = createProjectFolder(temporaryFolders, files);

		await connectContextRepository(connectionInput(project), testProvider(remote.bare));

		expect(getChangedContextFiles(project)).toEqual([]);
	});

	it('reports instance-only files as untracked', async () => {
		const remote = createRemoteRepository(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: same\n'),
		});
		const project = createProjectFolder(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: same\n'),
			'extra.md': Buffer.from('extra\n'),
		});

		await connectContextRepository(connectionInput(project), testProvider(remote.bare));

		expect(getChangedContextFiles(project)).toEqual([{ path: '/extra.md', kind: 'untracked' }]);
	});

	it('reports drifted files as modified', async () => {
		const remote = createRemoteRepository(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: remote\n'),
		});
		const project = createProjectFolder(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: instance\n'),
		});

		await connectContextRepository(connectionInput(project), testProvider(remote.bare));

		expect(getChangedContextFiles(project)).toEqual([{ path: '/nao_config.yaml', kind: 'modified' }]);
	});

	it('publishes the current files when the remote has no commits', async () => {
		const root = createTemporaryFolder(temporaryFolders, 'nao-context-connect-empty-');
		const bare = join(root, 'remote.git');
		runGit(root, ['init', '--bare', '--quiet', '--initial-branch=main', bare]);
		const project = createProjectFolder(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: deployed\n'),
			'context/model.md': Buffer.from('model\n'),
		});

		const result = await connectContextRepository(connectionInput(project), testProvider(bare));

		expect(result.connectionType).toBe('published-initial-commit');
		expect(runGit(project, ['rev-parse', 'HEAD']).toString().trim()).toBe(
			runGit(root, ['--git-dir', bare, 'rev-parse', 'refs/heads/main']).toString().trim(),
		);
		expect(getChangedContextFiles(project)).toEqual([]);
	});

	it('removes newly created Git metadata when connection fails', async () => {
		const project = createProjectFolder(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: deployed\n'),
		});
		const missingRemote = join(project, '..', 'missing.git');

		await expect(connectContextRepository(connectionInput(project), testProvider(missingRemote))).rejects.toThrow();

		expect(existsSync(join(project, '.git'))).toBe(false);
		expect(snapshotWorkingFiles(project)).toEqual({
			'nao_config.yaml': Buffer.from('project_name: deployed\n'),
		});
	});

	it('rejects an invalid repository name before initializing Git', async () => {
		const project = createProjectFolder(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: deployed\n'),
		});

		await expect(
			connectContextRepository(
				{ ...connectionInput(project), repoFullName: '--upload-pack=malicious' },
				testProvider('/unused'),
			),
		).rejects.toThrow('owner/name');

		expect(existsSync(join(project, '.git'))).toBe(false);
	});

	it('refuses existing repositories and entrypoint-managed Git contexts', async () => {
		const existingRepository = createProjectFolder(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: existing\n'),
		});
		initRepository(existingRepository);

		await expect(
			connectContextRepository(connectionInput(existingRepository), testProvider('/unused')),
		).rejects.toThrow('already inside a Git repository');

		const managedProject = createProjectFolder(temporaryFolders, {
			'nao_config.yaml': Buffer.from('project_name: managed\n'),
		});
		process.env.NAO_CONTEXT_SOURCE = 'git';
		await expect(
			connectContextRepository(connectionInput(managedProject), testProvider('/unused')),
		).rejects.toThrow('NAO_CONTEXT_SOURCE=git');
	});
});

function initRepository(folder: string): void {
	runGit(folder, ['init', '--quiet', '--initial-branch=main']);
}

function commitFiles(folder: string): void {
	runGit(folder, ['add', '-A']);
	runGit(folder, [
		'-c',
		'user.name=Test User',
		'-c',
		'user.email=test@example.com',
		'commit',
		'--quiet',
		'-m',
		'fixture',
	]);
}

function addGithubOrigin(folder: string): void {
	runGit(folder, ['remote', 'add', 'origin', 'https://github.com/nao/context.git']);
}

function runGit(folder: string, args: string[]): Buffer {
	return execFileSync('git', args, {
		cwd: folder,
		stdio: 'pipe',
		timeout: 5_000,
	});
}

function connectionInput(projectFolder: string) {
	return {
		projectFolder,
		provider: 'github' as const,
		repoFullName: 'nao/connected',
		branch: 'main',
		token: 'test-token',
	};
}

function testProvider(authenticatedUrl: string): ContextRepositoryProvider {
	return {
		authenticatedRepoUrl: () => authenticatedUrl,
		publicRepoUrl: () => 'https://github.com/nao/connected.git',
		getUserGitIdentity: async () => ({ name: 'Test User', email: 'test@example.com' }),
		coAuthor: { name: 'nao', email: 'naoagent@getnao.io' },
	};
}

function createRemoteRepository(
	temporaryFolders: string[],
	files: Record<string, Buffer>,
): { bare: string; seed: string } {
	const root = createTemporaryFolder(temporaryFolders, 'nao-context-connect-remote-');
	const bare = join(root, 'remote.git');
	const seed = join(root, 'seed');
	mkdirSync(seed);
	runGit(root, ['init', '--bare', '--quiet', '--initial-branch=main', bare]);
	initRepository(seed);
	writeFiles(seed, files);
	commitFiles(seed);
	runGit(seed, ['push', '--quiet', bare, 'main']);
	return { bare, seed };
}

function createProjectFolder(temporaryFolders: string[], files: Record<string, Buffer>): string {
	const project = createTemporaryFolder(temporaryFolders, 'nao-context-connect-project-');
	writeFiles(project, files);
	return project;
}

function createTemporaryFolder(temporaryFolders: string[], prefix: string): string {
	const folder = mkdtempSync(join(tmpdir(), prefix));
	temporaryFolders.push(folder);
	return folder;
}

function writeFiles(root: string, files: Record<string, Buffer>): void {
	for (const [filePath, content] of Object.entries(files)) {
		const target = join(root, filePath);
		mkdirSync(dirname(target), { recursive: true });
		writeFileSync(target, content);
	}
}

function snapshotWorkingFiles(root: string): Record<string, Buffer> {
	const snapshot: Record<string, Buffer> = {};
	for (const entry of readdirSync(root, { recursive: true, withFileTypes: true })) {
		const parentPath = entry.parentPath ?? entry.path;
		const absolutePath = join(parentPath, entry.name);
		const relativePath = relative(root, absolutePath);
		if (relativePath === '.git' || relativePath.startsWith(`.git/`) || !entry.isFile()) {
			continue;
		}
		snapshot[relativePath] = readFileSync(absolutePath);
	}
	return snapshot;
}
