project_name: example
databases:
- name: duckdb-jaffle-shop
  templates:
  - columns
  - preview
  profiling:
    refresh_policy: "interval" # "always", "interval", or "once"
    interval_days: 1
  include: []
  exclude: []
  type: duckdb
  path: ./jaffle_shop.duckdb
repos:
- name: dbt
  url: https://github.com/dbt-labs/jaffle_shop_duckdb.git
  branch: null
notion: null
llm:
  providers:
  - provider: openai
    api_key: sk-test
    models:
    - name: gpt-4.1
      id: gpt-4.1
    - name: gpt-4.1-turbo-mini-2026-07-19
      id: gpt-4.1-turbo-mini-2026-07-19
slack: null
