export interface SettingsSearchEntry {
	page: string;
	pageLabel: string;
	section?: string;
	title: string;
	description?: string;
	keywords?: string[];
	search?: Record<string, string>;
	adminOnly?: boolean;
	/** Visible to admins and context admins (observability surfaces). */
	adminOrContextAdmin?: boolean;
	cloudHidden?: boolean;
	cloudOnly?: boolean;
}

export const settingsSearchIndex: SettingsSearchEntry[] = [
	// ── Account ──────────────────────────────────────────────
	{
		page: '/settings/account',
		pageLabel: 'Account',
		title: 'Profile',
		description: 'Manage your name, email, and sign out.',
		keywords: ['name', 'email', 'sign out', 'logout', 'avatar'],
	},
	{
		page: '/settings/account',
		pageLabel: 'Account',
		section: 'General Settings',
		title: 'Sound notification',
		description: 'Play a sound when the agent finishes responding.',
		keywords: ['audio', 'alert', 'notification sound'],
	},
	{
		page: '/settings/account',
		pageLabel: 'Account',
		section: 'General Settings',
		title: 'Tool Call Density',
		description: 'Adjust how much detail is shown for tool calls.',
		keywords: ['compact', 'detailed', 'collapse', 'expand', 'tool calls', 'density', 'verbosity'],
	},
	{
		page: '/settings/account',
		pageLabel: 'Account',
		section: 'General Settings',
		title: 'Theme',
		description: 'Choose how nao looks.',
		keywords: ['dark mode', 'light mode', 'appearance', 'color scheme'],
	},
	{
		page: '/settings/account',
		pageLabel: 'Account',
		section: 'General Settings',
		title: 'Newsletter',
		description: 'Subscribe to nao product updates, release notes, and analytics agent tips.',
		keywords: ['email', 'mail', 'subscribe', 'updates', 'release notes'],
	},
	{
		page: '/settings/account',
		pageLabel: 'Account',
		title: 'GitLab',
		description: 'Connect your GitLab account for automations.',
		keywords: ['gitlab', 'automations', 'automation', 'merge request'],
	},
	{
		page: '/settings/account',
		pageLabel: 'Account',
		title: 'Danger Zone',
		description: 'Delete your account or perform other destructive actions.',
		keywords: ['delete account', 'remove'],
	},

	// ── Organization ─────────────────────────────────────────
	{
		page: '/settings/organization',
		pageLabel: 'Organization Settings',
		title: 'Members',
		description: 'Manage the members of your organization.',
		keywords: ['users', 'invite', 'add member', 'roles', 'team'],
	},
	{
		page: '/settings/organization',
		pageLabel: 'Organization Settings',
		title: 'Projects',
		description: 'See every project in your organization and the access you have to each one.',
		keywords: ['project list', 'access'],
	},
	{
		page: '/settings/organization',
		pageLabel: 'Organization Settings',
		title: 'Import from GitHub',
		description: 'Connect your GitHub account and import a repository as a project.',
		keywords: ['github', 'repository', 'repo', 'import', 'git', 'integration', 'clone'],
	},
	{
		page: '/settings/organization',
		pageLabel: 'Organization Settings',
		title: 'Import from GitLab',
		description: 'Connect your GitLab account and import a project as a nao project.',
		keywords: ['gitlab', 'repository', 'repo', 'import', 'git', 'integration', 'clone', 'merge request'],
	},
	{
		page: '/settings/organization',
		pageLabel: 'Organization Settings',
		title: 'Sign-in domains',
		description:
			'Users who sign in with Google using one of these verified email domains automatically join this organization.',
		keywords: ['sso', 'google', 'domain', 'email domain', 'allowlist', 'auto join', 'workspace', 'verified'],
		cloudOnly: true,
	},
	{
		page: '/settings/organization',
		pageLabel: 'Organization Settings',
		title: 'Organization API Keys',
		description: 'Generate organization-scoped API keys for actions like deploying a project from the nao CLI.',
		keywords: ['api key', 'deploy key', 'token', 'credentials'],
	},

	// ── Project > General ────────────────────────────────────
	{
		page: '/settings/project',
		pageLabel: 'General',
		title: 'Project Information',
		description: 'View your project name and path.',
		keywords: ['project name', 'project path'],
	},
	{
		page: '/settings/project',
		pageLabel: 'General',
		title: 'Environment Variables',
		description: 'Set environment variables referenced in nao_config.yaml.',
		keywords: ['env', 'environment', 'variable', 'secret', 'credential', 'config', 'jinja'],
		adminOnly: true,
	},
	{
		page: '/settings/project',
		pageLabel: 'General',
		title: 'Google Credentials',
		description: 'Configure Google service account credentials for BigQuery and other Google services.',
		keywords: ['google', 'bigquery', 'service account', 'gcp'],
		adminOnly: true,
	},
	{
		page: '/settings/project',
		pageLabel: 'General',
		title: 'Date format',
		description: 'Choose how dates are displayed in charts, tooltips and query result tables.',
		keywords: [
			'date',
			'format',
			'locale',
			'european',
			'american',
			'iso',
			'dd/mm/yyyy',
			'mm/dd/yyyy',
			'custom',
			'pattern',
		],
	},

	// ── Project > Models ─────────────────────────────────────
	{
		page: '/settings/project/models',
		pageLabel: 'Models',
		title: 'LLM Configuration',
		description: 'Configure the LLM providers for the agent in this project.',
		keywords: [
			'openai',
			'anthropic',
			'google',
			'qwen',
			'minimax',
			'moonshot',
			'kimi',
			'llm',
			'model',
			'provider',
			'api key',
			'openai compatible',
			'base url',
			'endpoint',
			'vllm',
			'litellm',
			'self-hosted',
		],
		adminOnly: true,
	},
	{
		page: '/settings/project/models',
		pageLabel: 'Models',
		title: 'Model parameters',
		description:
			'Fine-tune per-model inference parameters like temperature, top_p, top_k, max tokens and thinking effort.',
		keywords: [
			'temperature',
			'top_p',
			'top p',
			'top_k',
			'top k',
			'max tokens',
			'thinking',
			'reasoning',
			'inference',
			'sampling',
			'claude',
		],
	},
	{
		page: '/settings/project/models',
		pageLabel: 'Models',
		title: 'Default models',
		description: 'Choose which models nao uses for background tasks that run without an explicit model selection.',
		keywords: [
			'default model',
			'background',
			'live story',
			'title generation',
			'compaction',
			'context recommendations',
			'summary model',
			'extractor model',
			'fallback',
			'per category',
		],
		adminOnly: true,
	},
	{
		page: '/settings/project/models',
		pageLabel: 'Models',
		title: 'Transcription',
		description: 'Configure speech-to-text transcription provider and model.',
		keywords: ['voice', 'speech', 'microphone', 'whisper', 'stt'],
	},

	// ── Project > Agent ──────────────────────────────────────
	{
		page: '/settings/project/agent',
		pageLabel: 'Agent',
		section: 'Memory',
		title: 'Project Memory',
		description: 'Memories enable nao to remember preferences and facts about team members.',
		keywords: ['remember', 'learn', 'personalization'],
	},
	{
		page: '/settings/project/agent',
		pageLabel: 'Agent',
		title: 'Web search',
		description: 'Allow the agent to search the web for up-to-date information when answering questions.',
		keywords: ['internet', 'browse', 'fetch', 'online'],
	},
	{
		page: '/settings/project/agent',
		pageLabel: 'Agent',
		title: 'Saved Prompts',
		description: 'Save repeatable, customizable prompts for the agent to follow.',
		keywords: ['prompt template', 'instruction', 'preset'],
	},
	{
		page: '/settings/project/agent',
		pageLabel: 'Agent',
		title: 'Maps',
		description: 'Enable the agent to render query results on an interactive map.',
		keywords: ['display map', 'choropleth', 'points', 'scatter', 'bubble', 'geospatial'],
		adminOnly: true,
	},
	{
		page: '/settings/project/agent',
		pageLabel: 'Agent',
		title: 'GeoJSON Boundary Library',
		description: 'Add custom GeoJSON boundary sets the agent can use for choropleth maps.',
		keywords: ['geojson', 'boundaries', 'choropleth', 'map', 'regions', 'custom', 'polygon'],
		adminOnly: true,
	},
	{
		page: '/settings/project/agent',
		pageLabel: 'Agent',
		section: 'Experimental',
		title: 'Python sandboxing',
		description: 'Allow the agent to execute Python code in a secure sandboxed environment.',
		keywords: ['code execution', 'sandbox', 'python'],
	},
	{
		page: '/settings/project/agent',
		pageLabel: 'Agent',
		section: 'Experimental',
		title: 'Python execution duration',
		description: 'Configure how long Python code can run before it is stopped.',
		keywords: ['code execution', 'timeout', 'duration', 'python', 'seconds'],
	},
	{
		page: '/settings/project/agent',
		pageLabel: 'Agent',
		section: 'Experimental',
		title: 'Sandboxes',
		description: 'Allow the agent to use sandboxes to run code in a secure environment. Works with Boxlite.',
		keywords: ['boxlite', 'code execution'],
	},
	{
		page: '/settings/project/agent',
		pageLabel: 'Agent',
		section: 'Experimental',
		title: 'Display map',
		description:
			'Allow the agent to render query results with latitude and longitude columns on an interactive map.',
		keywords: ['map', 'geo', 'location', 'latitude', 'longitude', 'coordinates', 'spatial'],
	},
	{
		page: '/settings/project/agent',
		pageLabel: 'Agent',
		section: 'Experimental',
		title: 'Dangerous write permissions',
		description: 'Allow the agent to execute INSERT, UPDATE, DELETE and DDL SQL queries.',
		keywords: ['write', 'insert', 'update', 'delete', 'ddl', 'sql', 'permissions'],
	},

	// ── Project > MCP ────────────────────────────────────────
	{
		page: '/settings/project/mcp',
		pageLabel: 'MCP',
		section: 'Servers',
		search: { tab: 'servers' },
		title: 'MCP Servers',
		description:
			'Configure MCP servers in agent/mcps/mcp.json. nao discovers their tools into OpenAPI specs the agent explores on demand.',
		keywords: [
			'model context protocol',
			'tool',
			'integration',
			'extension',
			'discover',
			'openapi',
			'spec',
			'connect',
			'oauth',
		],
	},

	// ── Git ──────────────────────────────────────────────────
	{
		page: '/settings/git',
		pageLabel: 'Git',
		title: 'Connect your context files',
		description:
			'Connect the Git repository for context files so they can be edited and proposed as pull or merge requests.',
		keywords: [
			'github',
			'gitlab',
			'git',
			'oauth',
			'client id',
			'client secret',
			'redeploy',
			'restart',
			'repository',
			'repo',
			'connect',
			'disconnect',
			'context files',
			'account',
			'personal',
			'pull request',
			'pull request author',
			'merge request',
			'merge request author',
		],
		adminOrContextAdmin: true,
	},
	{
		page: '/settings/git',
		pageLabel: 'Git',
		title: 'Deployment repository',
		description: 'View the repository used for File Explorer commits and review requests.',
		keywords: [
			'git',
			'github',
			'gitlab',
			'deployment',
			'repository',
			'access token',
			'ssh key',
			'pull request author',
			'merge request author',
		],
		adminOrContextAdmin: true,
	},

	// ── Project > MCP Endpoint ──────────────────────────────
	{
		page: '/settings/project/mcp',
		pageLabel: 'MCP',
		section: 'Endpoints',
		search: { tab: 'endpoints' },
		title: 'MCP Server Endpoint',
		description: 'Allow external AI clients to connect to this workspace via MCP.',
		keywords: ['model context protocol', 'claude desktop', 'cursor', 'external', 'api', 'bearer'],
	},
	{
		page: '/settings/project/mcp',
		pageLabel: 'MCP',
		section: 'Endpoints',
		search: { tab: 'endpoints' },
		title: 'Sub-agent mode',
		description:
			"Exposes ask_nao and get_nao_answer — delegates the full analytics task to nao's agent. The reasoning trace is saved as a chat in the nao UI.",
		keywords: ['ask_nao', 'get_nao_answer', 'agent', 'analytics', 'delegate', 'sub-agent'],
	},
	{
		page: '/settings/project/mcp',
		pageLabel: 'MCP',
		section: 'Endpoints',
		search: { tab: 'endpoints' },
		title: 'Context-layer mode',
		description:
			'Exposes ls_nao_context, grep_nao_context, read_nao_context, execute_sql, create_story, update_story — the client MCP drives the workflow step by step.',
		keywords: [
			'ls_nao_context',
			'grep_nao_context',
			'read_nao_context',
			'execute_sql',
			'create_story',
			'update_story',
			'sql',
			'query',
			'story',
			'context',
		],
	},

	// ── Storage ─────────────────────────────────────────────
	{
		page: '/settings/storage',
		pageLabel: 'Storage',
		title: 'Permanent Storage',
		description:
			'Review the durable storage backend where the agent saves files: local disk, an S3 bucket, or disabled.',
		keywords: [
			'storage',
			'permanent',
			'persistent',
			'file',
			'files',
			'save',
			'write',
			'upload',
			'attachment',
			'disabled',
			'off',
			'bucket',
			's3',
			'minio',
			'r2',
			'volume',
			'disk',
			'local',
			'max file size',
			'size limit',
			'quota',
		],
		adminOnly: true,
		cloudHidden: true,
	},
	{
		page: '/settings/storage',
		pageLabel: 'Storage',
		title: 'Storage Health',
		description: 'Check that nao can reach and write to the configured storage location.',
		keywords: ['health', 'status', 'reachable', 'connection', 'credentials', 'bucket access', 'writable'],
		adminOnly: true,
		cloudHidden: true,
	},
	{
		page: '/settings/storage',
		pageLabel: 'Storage',
		title: 'Storage Usage',
		description: 'See how many files are stored and how much space they take, for you or for every user.',
		keywords: [
			'usage',
			'stats',
			'statistics',
			'space',
			'size',
			'occupied',
			'files',
			'file count',
			'per user',
			'quota',
			'disk usage',
			'consumption',
			'my space',
		],
		cloudHidden: true,
	},

	// ── Project > Integrations ───────────────────────────────
	{
		page: '/settings/project/integrations/slack',
		pageLabel: 'Integrations',
		section: 'Slack',
		title: 'Slack Integration',
		description: 'Configure Slack app credentials, webhook, and bot behavior.',
		keywords: ['slack bot', 'slack app', 'slack webhook', 'messaging'],
	},
	{
		page: '/settings/project/integrations/slack',
		pageLabel: 'Integrations',
		section: 'Slack',
		title: 'Auto-create users from Slack',
		description: 'Automatically provision nao accounts for Slack senders whose email domain is in the allowlist.',
		keywords: ['sign up', 'provision', 'onboarding', 'domain', 'allowlist', 'whitelist', 'auto create'],
		adminOnly: true,
	},
	{
		page: '/settings/project/integrations/slack',
		pageLabel: 'Integrations',
		section: 'Slack',
		title: 'Reply only when mentioned',
		description:
			'Control whether nao answers every message in active Slack threads or only messages that tag the bot.',
		keywords: ['reply mode', 'mentions', 'tagged', 'thread replies', 'bot behavior'],
	},
	{
		page: '/settings/project/integrations/slack',
		pageLabel: 'Integrations',
		section: 'Slack',
		title: 'Slack transport mode',
		description: 'Switch between Webhook and Socket Mode for Slack delivery.',
		keywords: [
			'slack socket mode',
			'slack websocket',
			'private vpc',
			'air-gapped',
			'firewall',
			'app token',
			'xapp',
		],
	},
	{
		page: '/settings/project/integrations/slack',
		pageLabel: 'Integrations',
		section: 'Slack',
		title: '/new slash command',
		description:
			'Users can type /new in Slack to start a fresh chat in private conversation and clear the previous main context.',
		keywords: ['slack new chat', 'slack reset', 'slack fresh session', 'slash command', '/new'],
	},
	{
		page: '/settings/project/integrations/teams',
		pageLabel: 'Integrations',
		section: 'Microsoft Teams',
		title: 'Microsoft Teams Integration',
		description: 'Configure Teams app credentials, messaging endpoint, and bot behavior.',
		keywords: ['teams bot', 'azure bot', 'teams app', 'messaging'],
	},
	{
		page: '/settings/project/integrations/telegram',
		pageLabel: 'Integrations',
		section: 'Telegram',
		title: 'Telegram Integration',
		description: 'Configure Telegram bot credentials, webhook, and bot behavior.',
		keywords: ['telegram bot', 'telegram webhook', 'messaging'],
	},
	{
		page: '/settings/project/integrations/telegram',
		pageLabel: 'Integrations',
		section: 'Telegram',
		title: 'Linking Code',
		description: 'Send /login <code> to the Telegram bot you want to link.',
		keywords: ['link', 'login', 'telegram'],
	},
	{
		page: '/settings/project/integrations/whatsapp',
		pageLabel: 'Integrations',
		section: 'WhatsApp',
		title: 'WhatsApp Integration',
		description: 'Configure WhatsApp app credentials, webhook, and bot behavior.',
		keywords: ['whatsapp bot', 'whatsapp webhook', 'messaging'],
	},
	{
		page: '/settings/project/integrations/whatsapp',
		pageLabel: 'Integrations',
		section: 'WhatsApp',
		title: 'Linking Code',
		description: 'Send /login <code> from the WhatsApp number you want to link.',
		keywords: ['link', 'login', 'phone number'],
	},

	// ── Project > Team ───────────────────────────────────────
	{
		page: '/settings/project/team',
		pageLabel: 'Team',
		title: 'Team Members',
		description: 'Manage the members of your project.',
		keywords: ['users', 'invite', 'add member', 'roles', 'project members'],
	},
	{
		page: '/settings/project/team',
		pageLabel: 'Team',
		section: 'Budgets',
		title: 'Budgets',
		description: 'Limit the budgets of your most expensive providers.',
		keywords: ['budget', 'provider limit', 'spend', 'cost'],
	},
	{
		page: '/settings/project/team',
		pageLabel: 'Team',
		section: 'Budgets',
		title: 'Spend per user',
		description: 'Review current-period spend for each project member.',
		keywords: ['user budget', 'member spend', 'cost per user'],
		adminOnly: true,
	},

	// ── Usage & Costs ────────────────────────────────────────
	{
		page: '/settings/usage',
		pageLabel: 'Usage, costs & replay',
		title: 'Messages',
		description: 'How many messages have been sent across all chats?',
		keywords: ['usage', 'analytics', 'statistics'],
		adminOnly: true,
	},
	{
		page: '/settings/usage',
		pageLabel: 'Usage, costs & replay',
		title: 'Tokens',
		description: 'Tokens used across all chats.',
		keywords: ['token usage', 'input tokens', 'output tokens'],
		adminOnly: true,
	},
	{
		page: '/settings/usage',
		pageLabel: 'Usage, costs & replay',
		title: 'Cost',
		description: 'Estimated cost in USD based on token usage and model pricing.',
		keywords: ['price', 'billing', 'expense', 'spending'],
		adminOnly: true,
	},
	{
		page: '/settings/usage',
		pageLabel: 'Usage, costs & replay',
		title: 'Feedbacks',
		description: 'Feedbacks users have given to the agent during their sessions.',
		keywords: ['thumbs up', 'thumbs down', 'rating', 'review'],
		adminOnly: true,
	},

	// ── Usage & Costs > Chats Replay ─────────────────────────
	{
		page: '/settings/usage',
		pageLabel: 'Chats replay',
		title: 'Chats Replay',
		description: 'Replay and review past chat conversations.',
		keywords: ['history', 'conversation', 'replay', 'review'],
		adminOrContextAdmin: true,
	},

	// ── Context Recommendations ──────────────────────────────
	{
		page: '/settings/recommendations',
		pageLabel: 'Recommendations',
		title: 'Context Recommendations',
		description: 'Review and act on context recommendations for your project.',
		keywords: [
			'context',
			'recommendations',
			'acknowledge',
			'snooze',
			'dismiss',
			'insights',
			'frequency',
			'schedule',
			'daily',
			'weekly',
			'monthly',
			'repository',
			'github',
			'pull request',
			'batch pr',
			'batch pull request',
			'copy prompt',
			'agent prompt',
			'yolo',
			'auto',
			'automatic',
			'pr',
			'tool errors',
			'hallucination',
			'semantic missing',
			'context bloat',
			'token cost',
			'skills',
			'root cause',
			'fix target',
			'category',
			'config',
			'applied',
			'dismissed',
		],
		adminOrContextAdmin: true,
	},

	// ── Logs ─────────────────────────────────────────────────
	{
		page: '/settings/logs',
		pageLabel: 'Server logs',
		title: 'Logs',
		description: 'Real-time backend logs with auto-refresh.',
		keywords: ['error', 'warn', 'debug', 'info', 'terminal', 'console'],
		adminOnly: true,
		cloudHidden: true,
	},

	// ── Enterprise ───────────────────────────────────────────
	{
		page: '/settings/enterprise',
		pageLabel: 'License & branding',
		section: 'License',
		search: { tab: 'license' },
		title: 'License',
		description: 'View the status of your nao Enterprise license.',
		keywords: ['enterprise', 'license', 'subscription', 'activation', 'sso', 'nao_license', 'ee'],
		adminOnly: true,
		cloudHidden: true,
	},
	{
		page: '/settings/enterprise',
		pageLabel: 'License & branding',
		section: 'License',
		search: { tab: 'license' },
		title: 'Enterprise features',
		description: 'Enterprise capabilities enabled by your license.',
		keywords: ['features', 'sso', 'enterprise', 'plan'],
		adminOnly: true,
		cloudHidden: true,
	},
	{
		page: '/settings/enterprise',
		pageLabel: 'License & branding',
		section: 'License',
		search: { tab: 'license' },
		title: 'Single sign-on token',
		description: 'Inspect the claims your identity provider sent and how they resolved to a role.',
		keywords: [
			'sso',
			'oidc',
			'okta',
			'token',
			'claims',
			'groups',
			'group mapping',
			'role',
			'debug',
			'id token',
			'entra',
			'keycloak',
		],
		adminOnly: true,
		cloudHidden: true,
	},
	{
		page: '/settings/enterprise',
		pageLabel: 'License & branding',
		section: 'Branding',
		search: { tab: 'branding' },
		title: 'White-label branding',
		description: 'Replace the nao name, logo, favicon and brand color with your own branding. Enterprise feature.',
		keywords: [
			'white label',
			'whitelabel',
			'branding',
			'logo',
			'favicon',
			'tab',
			'title',
			'customize',
			'signup',
			'login',
			'enterprise',
			'color',
			'colour',
			'theme',
			'primary',
		],
		adminOnly: true,
		cloudHidden: true,
	},
	{
		page: '/settings/enterprise',
		pageLabel: 'License & branding',
		section: 'Branding',
		search: { tab: 'branding' },
		title: 'Brand color',
		description: 'Set a custom primary color for buttons, links and accents across the app.',
		keywords: [
			'color',
			'colour',
			'brand color',
			'brand colour',
			'primary color',
			'theme color',
			'accent',
			'hex',
			'enterprise',
		],
		adminOnly: true,
		cloudHidden: true,
	},
	{
		page: '/settings/enterprise',
		pageLabel: 'License & branding',
		section: 'Branding',
		search: { tab: 'branding' },
		title: 'Logo',
		description: 'Replace the logo shown in the sidebar and on the login and sign-up pages.',
		keywords: ['logo', 'sidebar', 'login logo', 'signup logo', 'auth', 'brand', 'enterprise'],
		adminOnly: true,
		cloudHidden: true,
	},
	{
		page: '/settings/enterprise',
		pageLabel: 'License & branding',
		section: 'Branding',
		search: { tab: 'branding' },
		title: 'Favicon',
		description: 'Replace the favicon shown in the browser tab.',
		keywords: ['favicon', 'icon', 'tab', 'enterprise'],
		adminOnly: true,
		cloudHidden: true,
	},
	{
		page: '/settings/enterprise',
		pageLabel: 'License & branding',
		section: 'Branding',
		search: { tab: 'branding' },
		title: 'Browser tab title',
		description: 'Rename the browser tab shown to your users.',
		keywords: ['tab title', 'page title', 'name', 'enterprise'],
		adminOnly: true,
		cloudHidden: true,
	},

	// ── Memory ───────────────────────────────────────────────
	{
		page: '/settings/memory',
		pageLabel: 'Memory',
		title: 'Memory',
		description: 'Memories enables nao to learn about you and your preferences over time.',
		keywords: ['remember', 'learn', 'personalization', 'preferences'],
	},
	{
		page: '/settings/memory',
		pageLabel: 'Memory',
		title: 'Saved Memories',
		description: 'Review and manage memory preferences and what the agent has remembered.',
		keywords: ['remembered facts', 'memory list'],
	},

	// ── Context Explorer ─────────────────────────────────────
	{
		page: '/settings/context-explorer',
		pageLabel: 'File Explorer',
		title: 'File Explorer',
		description: 'Browse and inspect the files and context available to the agent.',
		keywords: ['files', 'context', 'documents', 'knowledge base'],
		adminOrContextAdmin: true,
	},
];
