"""Markers for agent-managed and manual context files written during sync."""

from __future__ import annotations

import re
from enum import Enum
from pathlib import Path


class ContextFileKind(str, Enum):
    """Origin of a context file written during sync."""

    GENERATED = "generated"
    MANUAL = "manual"


_MESSAGES: dict[ContextFileKind, str] = {
    ContextFileKind.GENERATED: "This file is managed and generated by the agent, do not modify it!",
    ContextFileKind.MANUAL: "These are manual notes you want the agent to keep in mind, safe to edit.",
}

_MARKER_PATTERN = re.compile(r"<!--\s*nao:(generated|manual)\b")


def marker_for(kind: ContextFileKind) -> str:
    """Build the single-line HTML marker carrying the stable token and human message."""
    return f"<!-- nao:{kind.value} | {_MESSAGES[kind]} -->"


def kind_of(content: str) -> ContextFileKind | None:
    """Classify a file from its content, or return None when no known marker is present."""
    match = _MARKER_PATTERN.search(content)
    if match is None:
        return None
    return ContextFileKind(match.group(1))


def with_generated_marker(content: str) -> str:
    """Prepend the generated-file marker to freshly rendered content."""
    return f"{marker_for(ContextFileKind.GENERATED)}\n\n{content}"


def ensure_annotations_file(folder: Path) -> None:
    """Create the annotations file in a table folder once, never overwriting it."""
    annotations_file = folder / "annotations.md"
    if annotations_file.exists():
        return
    annotations_file.write_text(f"{marker_for(ContextFileKind.MANUAL)}\n")
