import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { SettingsCard } from '@/components/ui/settings-card';
import { SettingsControlRow } from '@/components/ui/settings-toggle-row';
import { Switch } from '@/components/ui/switch';
import { trpc } from '@/main';

interface SettingsStoryPluginsProps {
	isAdmin: boolean;
}

export function SettingsStoryPlugins({ isAdmin }: SettingsStoryPluginsProps) {
	const queryClient = useQueryClient();
	const agentSettings = useQuery(trpc.project.getAgentSettings.queryOptions());

	const updateAgentSettings = useMutation(
		trpc.project.updateAgentSettings.mutationOptions({
			onSuccess: () => {
				queryClient.invalidateQueries({
					queryKey: trpc.project.getAgentSettings.queryOptions().queryKey,
				});
			},
		}),
	);

	const storyPluginsEnabled = agentSettings.data?.storyPlugins?.enabled ?? false;

	const handleStoryPluginsChange = (enabled: boolean) => {
		updateAgentSettings.mutate({ storyPlugins: { enabled } });
	};

	return (
		<SettingsCard
			title='Vibe coded plugins'
			description='Allow the agent to generate custom interactive plugin blocks inside stories.'
		>
			<SettingsControlRow
				id='story-plugins'
				label='Enable story plugins'
				description='Allows self-contained JavaScript plugins generated by the agent to run in stories.'
				control={
					<Switch
						id='story-plugins'
						checked={storyPluginsEnabled}
						onCheckedChange={handleStoryPluginsChange}
						disabled={!isAdmin || updateAgentSettings.isPending}
					/>
				}
			/>
		</SettingsCard>
	);
}
