/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatLayoutRouteImport } from './routes/_chat-layout'
import { Route as ChatLayoutIndexRouteImport } from './routes/_chat-layout.index'
import { Route as ChatLayoutChatIdRouteImport } from './routes/_chat-layout.$chatId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatLayoutRoute = ChatLayoutRouteImport.update({
  id: '/_chat-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatLayoutIndexRoute = ChatLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatLayoutRoute,
} as any)
const ChatLayoutChatIdRoute = ChatLayoutChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$chatId': typeof ChatLayoutChatIdRoute
  '/': typeof ChatLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$chatId': typeof ChatLayoutChatIdRoute
  '/': typeof ChatLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat-layout': typeof ChatLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_chat-layout/$chatId': typeof ChatLayoutChatIdRoute
  '/_chat-layout/': typeof ChatLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/signup' | '/$chatId' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup' | '/$chatId' | '/'
  id:
    | '__root__'
    | '/_chat-layout'
    | '/login'
    | '/signup'
    | '/_chat-layout/$chatId'
    | '/_chat-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatLayoutRoute: typeof ChatLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat-layout': {
      id: '/_chat-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ChatLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat-layout/': {
      id: '/_chat-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatLayoutIndexRouteImport
      parentRoute: typeof ChatLayoutRoute
    }
    '/_chat-layout/$chatId': {
      id: '/_chat-layout/$chatId'
      path: '/$chatId'
      fullPath: '/$chatId'
      preLoaderRoute: typeof ChatLayoutChatIdRouteImport
      parentRoute: typeof ChatLayoutRoute
    }
  }
}

interface ChatLayoutRouteChildren {
  ChatLayoutChatIdRoute: typeof ChatLayoutChatIdRoute
  ChatLayoutIndexRoute: typeof ChatLayoutIndexRoute
}

const ChatLayoutRouteChildren: ChatLayoutRouteChildren = {
  ChatLayoutChatIdRoute: ChatLayoutChatIdRoute,
  ChatLayoutIndexRoute: ChatLayoutIndexRoute,
}

const ChatLayoutRouteWithChildren = ChatLayoutRoute._addFileChildren(
  ChatLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatLayoutRoute: ChatLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
